# 실행 모드
mig.progress.mode=test

# DB 접속 정보
mig.db.driverClassName=com.mysql.cj.jdbc.Driver
mig.db.url=jdbc:mysql://127.0.0.1:3306/testdb?serverTimezone=Asia/Seoul
mig.db.username=test
mig.db.password=test
